site_name: Data at the SAFE Project
repo_url: https://github.com/ImperialCollegeLondon/safedata_validator/
theme: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - custom.css
use_directory_urls: false
nav:
  - 'Introduction': 'index.md'
  - 'Data availability': 'availability.md'
  - 'Data format overview': 'data_format/overview.md'
  - 'Excel format details':
    - 'Summary worksheet': 'data_format/summary.md'
    - 'Taxa worksheet': 'data_format/taxa.md'
    - 'Locations worksheet': 'data_format/locations.md'
    - 'Data worksheets': 'data_format/data.md'
  - 'Other file formats': 'data_format/other_formats.md'
  - 'Data format FAQs': 'faqs.md'
  - 'The safedata_validator package':
    - 'Usage': 'safedata_validator/usage.md'
    - 'Installation': 'safedata_validator/install.md'
    - 'Building local GBIF': 'safedata_validator/build_local_gbif.md'
    - 'GBIF validation notes': 'safedata_validator/gbif_validation.md'
  - 'Build notes': build_notes.md
